import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'services/auth_service.dart';
import 'screens/sign_in_screen.dart';
import 'screens/home_screen.dart';

/// When true, the app talks to the local Firebase Emulator Suite instead of a
/// real project. Enable at run time with:
///   flutter run --dart-define=USE_EMULATOR=true
const bool _useEmulator =
    bool.fromEnvironment('USE_EMULATOR', defaultValue: false);

/// Host the emulators are reachable on. `localhost` works for iOS simulators,
/// macOS, and web; the Android emulator reaches the host machine via 10.0.2.2.
String get _emulatorHost {
  if (_useEmulator && defaultTargetPlatform == TargetPlatform.android) {
    return '10.0.2.2';
  }
  return 'localhost';
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // firebase_options.dart is generated by `flutterfire configure` and is
  // intentionally git-ignored. Against the emulator we don't need real
  // credentials, so a demo project id is enough.
  await Firebase.initializeApp(
    options: _useEmulator
        ? const FirebaseOptions(
            apiKey: 'demo-key',
            appId: '1:0:android:demo',
            messagingSenderId: '0',
            projectId: 'demo-mle',
          )
        : null,
  );

  if (_useEmulator) {
    final host = _emulatorHost;
    await FirebaseAuth.instance.useAuthEmulator(host, 9099);
    FirebaseFirestore.instance.useFirestoreEmulator(host, 8080);
    FirebaseFunctions.instance.useFunctionsEmulator(host, 5001);
  }

  runApp(const MleApp());
}

class MleApp extends StatelessWidget {
  const MleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Provider<AuthService>(
      create: (_) => AuthService(),
      child: MaterialApp(
        title: 'MLE',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorSchemeSeed: const Color(0xFF00A86B), // pitch green
          useMaterial3: true,
        ),
        home: const AuthGate(),
      ),
    );
  }
}

/// Routes to the sign-in screen or the home screen based on auth state.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = context.read<AuthService>();
    return StreamBuilder<User?>(
      stream: auth.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        return snapshot.hasData ? const HomeScreen() : const SignInScreen();
      },
    );
  }
}
